Speed improvements and multiple projection networks
mrcoliva/bark-ml pull request #17
Opened 2020-07-18 20:48 UTC by mrcoliva

2020-07-18 21:18 UTC, lesilvan requested changes
From my perspective this merge is not yet usefull. First of all, the test examples fail. Second, a lot of old files are merged and new structure/files killed. Third, useless files for tf2gnn are readded, which were removed before.

I would recommend to first merge develop into activate_nitro and then merge back into it (then you have to look out to not loose your changes), but otherwise we kill all tests once more.

2020-07-18 21:18 UTC, lesilvan commented on examples/data_generation.py
>  from absl import flags
This file has been moved to another place. It makes no sense to move it back.

2020-07-18 21:18 UTC, lesilvan commented on supervised_learning/py_learn_actor_tests.py
>  # https://opensource.org/licenses/MIT
Why change all the file?

2020-07-19 06:58 UTC, mrcoliva commented
@lesilvan There has been a few unintended changes made by the automatic merge. I resolved them as far as I know.

2020-07-19 08:31 UTC, lesilvan commented on supervised_learning/BUILD
> -py_test(
This file should not be changed either.

2020-07-19 08:34 UTC, lesilvan requested changes
supervised_learning/BUILD should not be changed by your branch. The rest looks OK for now, but as long as all tests do not run without error, I would not merge it.

2020-07-19 08:36 UTC, mrcoliva commented on supervised_learning/BUILD
> -py_test(
Fixed.

2020-07-19 08:41 UTC, lesilvan approved these changes

2020-07-19 09:09 UTC, lesilvan requested changes

2020-07-19 09:09 UTC, lesilvan commented on bark_ml/library_wrappers/lib_tf2_gnn/gnn_actor_network.py
> +    batch_size, feature_len = observations.shape
I think this is the problem. As we do not always batch_call this.

2020-07-19 11:52 UTC, merged

2020-07-19 11:53 UTC, lesilvan approved these changes